export const TYPES = {
  TOGGLE_MODAL: "TOGGLE_MODAL",
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  SET_ALL_BOOKS: "SET_ALL_BOOKS",
  HANDLE_CHANGE: "HANDLE_CHANGE",
  SET_RESULTS: "SET_RESULTS",
  TOGGLE_IS_SEARCHING: "TOGGLE_IS_SEARCHING",
  SET_DISPLAY: "SET_DISPLAY",
}
